<a href="https://colab.research.google.com/github/divyamsh8/DAV_LAB/blob/main/DAV_LAB_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Marks": [78,85,92,67],
    "Att": [88,90,95,72]
}
df=pd.DataFrame(data)
df.head()

    Name  Marks  Att
0    Anu     78   88
1  Rahul     85   90
2  Kiran     92   95
3  Priya     67   72

In [ ]:
df.shape

(4, 3)

In [ ]:
df["Marks"]

0    78
1    85
2    92
3    67
Name: Marks, dtype: int64

In [ ]:
df.iloc[0]

In [ ]:
df1=pd.read_csv("california_housing_test.csv")

In [ ]:
df1.head()

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df1)

In [ ]:
df.iloc[0:]

###  LAB-1

3/09/26

In [ ]:
import numpy as np
import pandas as pd
print("Numpy Version",np.__version__)
print("Pandas Version",pd.__version__)

In [ ]:
marks = np.array([78,85,92,67,88])
print("Marks:",marks)
print("Type: ",type(marks))

In [ ]:
print("Number of dimensions: ",marks.ndim)
print("Shape:",marks.shape)
print("Size:",marks.size)
print("Data Type:",marks.dtype)
print("Item Size:",marks.itemsize)

In [ ]:
print("Original:",marks)
print("Add 5:",marks+5)
print("Subtract 5:",marks-5)
print("Multiply 5:",marks*5)
print("Divide 5:",marks/5)
print("Power 5:",marks**5)
print("Modulus 5:",marks%5)

In [ ]:
print("sum:",marks.sum())
print("Mean:",marks.mean())
print("Max:",marks.max())
print("Min:",marks.min())
print("Standard Deviation:",marks.std())
print("Variance:",marks.var())
print("Product:",marks.prod())
print("Cumulative Sum:",marks.cumsum())
print("Cumulative Product:",marks.cumprod())
print("Sort:",np.sort(marks))
print("Sort in Descending Order:",np.sort(marks)[::-1])
print("Sort in Ascending Order:",np.sort(marks))

In [ ]:
print("First mark:",marks[0])
print("Last mark:",marks[-1])
print("First 3 marks:",marks[:3])
print("Marks after 3rd mark:",marks[3:])
print("Marks from 2nd to 4th:",marks[1:4])
print("Marks from 2nd to 4th with step 2:",marks[1:4:2])
print("Marks from 2nd to 4th with step 3:",marks[1:4:3])
print("Marks from 2nd to 4th with step 4:",marks[1:4:4])
print("Marks from 2nd to 4th with step 5:",marks[1:4:5])
print("Marks from 2nd to 4th with step 6:",marks[1:4:6])

In [ ]:
student_marks = np.array([[78,85,92],[67,88,76],[90,95,89]])
print("Student Marks:\n",student_marks)
print("Shape:",student_marks.shape)
print("Size:",student_marks.size)

In [ ]:
print("Mean of all values:",student_marks.mean())
print("Mean of each row:",student_marks.mean(axis=1))
print("Mean of each column:",student_marks.mean(axis=0))

In [ ]:
data ={
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch" : ["CSE","ECE","CSE","ECE"],
    "Marks": [78,85,92,67],
}
df=pd.DataFrame(data)
df

In [ ]:
print("Shape",df.shape)
print("Size",df.size)
print("Columns",df.columns)
print("Index",df.index)
print("Values",df.values)

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
print("Marks column",df['Marks'])
print("Marks column type",type(df['Marks']))
print("Branch and Marks",df[['Branch','Marks']])

In [ ]:
print("First row\n",df.iloc[0])
print("First two rows\n",df.iloc[:2])
print("First two rows and first two columns\n",df.iloc[:2,:2])

In [ ]:
high_scorers = df[df['Marks']>80]
print(high_scorers)

In [ ]:
print("Students from CSE:",df[df['Branch'] == "CSE"])

In [ ]:
data = {
    "Name": ["Anu","Rahul","Kiran","Priya","Divyamsh"],
    "Branch" : ["CSE","ECE","CSE","ECE","CSE"],
    "Marks": [78,85,92,67,100],
    "Atd": [82,67,77,96,100],
}
stu=pd.DataFrame(data)
stu

In [ ]:
print("\tOnly Name and Marks: \n",stu.iloc[:,:3:2])

In [ ]:
 print(stu[stu["Marks"]>80])
 print(stu[stu["Atd"]>80])

In [ ]:
print("\tOnly Name and Marks: \n",stu.iloc[:3])

In [ ]:
print(stu.iloc[:,2:3].mean())
print(stu.iloc[:,2:3].max())

In [ ]:
print(stu[stu['Branch']=="CSE"])

In [ ]:
 print(stu[(stu["Atd"]>85) & (stu["Marks"]> 80)])

### LAB-2