<a href="https://colab.research.google.com/github/divyamsh8/DAV_LAB/blob/main/Lab2_4_09_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,110],
    "Name": ["Anu","Bharat","Chetan","Divya","Esha","Farhan","Gaowri","Harish","Isha","Kiran","Kiran"],
    "Department": ["CSE","AIML","CSE","ISE","AIML","CSE","ISE","CSE","AIML","ISE","ISE"],
    "Gender":["F","M","M","F","F","M","F","M","F","M","M"],
    "Attendance":[92,85,78,95,88,None,91,73,86,80,80],
    "Python_Marks":[88,76,91,95,84,72,None,65,89,78,78],
    "Data_Structures_Marks":[82,79,94,90,87,68,92,None,85,74,74],
    "Final_Score":[85,77,93,92,86,70,91,67,87,76,76]
}

df=pd.DataFrame(data)
df

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93
3,104,Divya,ISE,F,95.0,95.0,90.0,92
4,105,Esha,AIML,F,88.0,84.0,87.0,86
5,106,Farhan,CSE,M,NaN,72.0,68.0,70
6,107,Gaowri,ISE,F,91.0,NaN,92.0,91
7,108,Harish,CSE,M,73.0,65.0,NaN,67
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
df.head()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93
3,104,Divya,ISE,F,95.0,95.0,90.0,92
4,105,Esha,AIML,F,88.0,84.0,87.0,86

In [ ]:
df.head(3)

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93

In [ ]:
df.tail()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
6,107,Gaowri,ISE,F,91.0,NaN,92.0,91
7,108,Harish,CSE,M,73.0,65.0,NaN,67
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
df.tail(3)

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
r,c=df.shape
print("Number of rows: ",r)
print("Number of columns: ",c)

Number of rows:  11
Number of columns:  8

In [ ]:
print(df.columns.tolist())

['Student_ID', 'Name', 'Department', 'Gender', 'Attendance', 'Python_Marks', 'Data_Structures_Marks', 'Final_Score']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             11 non-null     int64
 1   Name                   11 non-null     object
 2   Department             11 non-null     object
 3   Gender                 11 non-null     object
 4   Attendance             10 non-null     float64
 5   Python_Marks           10 non-null     float64
 6   Data_Structures_Marks  10 non-null     float64
 7   Final_Score            11 non-null     int64
dtypes: float64(3), int64(2), object(3)
memory usage: 836.0+ bytes

In [ ]:
print(df.dtypes)

Student_ID                 int64
Name                      object
Department                object
Gender                    object
Attendance               float64
Python_Marks             float64
Data_Structures_Marks    float64
Final_Score                int64
dtype: object

In [ ]:
print("Mean Python marks: ", df['Python_Marks'].mean())
print("Mean Total marks: ", df['Final_Score'].mean())

Mean Python marks:  81.6
Mean Total marks:  81.81818181818181

In [ ]:
print("Median Python marks: ", df['Python_Marks'].median())
print("Median Total marks: ", df['Final_Score'].median())

Median Python marks:  81.0
Median Total marks:  85.0

In [ ]:
print("Mode of Department: \n", df['Department'].mode())
print("Mode of Gender: \n", df['Gender'].mode())

Mode of Department:
 0    CSE
1    ISE
Name: Department, dtype: object
Mode of Gender:
 0    M
Name: Gender, dtype: object

In [ ]:
df.describe()

,Student_ID,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
count,11.000000,10.000000,10.000000,10.000000,11.000000
mean,105.909091,84.800000,81.600000,82.500000,81.818182
std,3.176619,6.972964,9.395034,8.644202,9.042325
min,101.000000,73.000000,65.000000,68.000000,67.000000
25%,103.500000,80.000000,76.500000,75.250000,76.000000
50%,106.000000,85.500000,81.000000,83.500000,85.000000
75%,108.500000,90.250000,88.750000,89.250000,89.000000
max,110.000000,95.000000,95.000000,94.000000,93.000000

In [ ]:
print("Python Marks")
print("Mean: ", df['Python_Marks'].mean())
print("Median: ", df['Python_Marks'].median())
print("Minimum: ", df['Python_Marks'].min())
print("Maximum: ", df['Python_Marks'].max())
print("Standard Deviation: ", df['Python_Marks'].std())
print("Variance: ", df['Python_Marks'].var())

Python Marks
Mean:  81.6
Median:  81.0
Minimum:  65.0
Maximum:  95.0
Standard Deviation:  9.395034149308168
Variance:  88.26666666666667

In [ ]:
df.isnull()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False

In [ ]:
print("Misssing Values in each coloumn",df.isnull().sum())

Misssing Values in each coloumn Student_ID               0
Name                     0
Department               0
Gender                   0
Attendance               1
Python_Marks             1
Data_Structures_Marks    1
Final_Score              0
dtype: int64

In [ ]:
missing_percentage= (df.isnull().sum()/len(df))*100
print(missing_percentage)

Student_ID               0.000000
Name                     0.000000
Department               0.000000
Gender                   0.000000
Attendance               9.090909
Python_Marks             9.090909
Data_Structures_Marks    9.090909
Final_Score              0.000000
dtype: float64

In [ ]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
display(df.iloc[:, [0, 1, 3, 4, 5, 6]])

    Student_ID    Name Gender  Attendance  Python_Marks  Data_Structures_Marks
0          101     Anu      F        92.0          88.0                   82.0
1          102  Bharat      M        85.0          76.0                   79.0
2          103  Chetan      M        78.0          91.0                   94.0
3          104   Divya      F        95.0          95.0                   90.0
4          105    Esha      F        88.0          84.0                   87.0
5          106  Farhan      M         NaN          72.0                   68.0
6          107  Gaowri      F        91.0           NaN                   92.0
7          108  Harish      M        73.0          65.0                    NaN
8          109    Isha      F        86.0          89.0                   85.0
9          110   Kiran      M        80.0          78.0                   74.0
10         110   Kiran      M        80.0          78.0                   74.0

In [ ]:
print("Number od duplicated rows",df.duplicated().sum())

Number od duplicated rows 1

In [ ]:
df[df.duplicated()]
print(df[df.duplicated()])

    Student_ID   Name Department Gender  Attendance  Python_Marks  \
10         110  Kiran        ISE      M        80.0          78.0

    Data_Structures_Marks  Final_Score
10                   74.0           76

In [ ]:
print(df.drop(2))

    Student_ID    Name Department Gender  Attendance  Python_Marks  \
0          101     Anu        CSE      F        92.0          88.0
1          102  Bharat       AIML      M        85.0          76.0
3          104   Divya        ISE      F        95.0          95.0
4          105    Esha       AIML      F        88.0          84.0
5          106  Farhan        CSE      M         NaN          72.0
6          107  Gaowri        ISE      F        91.0           NaN
7          108  Harish        CSE      M        73.0          65.0
8          109    Isha       AIML      F        86.0          89.0
9          110   Kiran        ISE      M        80.0          78.0
10         110   Kiran        ISE      M        80.0          78.0

    Data_Structures_Marks  Final_Score
0                    82.0           85
1                    79.0           77
3                    90.0           92
4                    87.0           86
5                    68.0           70
6                    92.0           91
7                     NaN           67
8                    85.0           87
9                    74.0           76
10                   74.0           76

In [ ]:
employee_data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Anu', 'Bharat', 'Chetan', 'Divya', 'Esha', 'Farhan', 'Gaowri', 'Harish'],
    'Department': ['CSE', 'AIML', 'CSE', 'ISE', 'AIML', 'CSE', 'ISE', 'CSE'],
    'Salary': [60000, 55000, 62000, 58000, 61000, 59000, 57000, 63000],
    'Rating': [4.5, 4.2, 4.8, 4.6, 4.7, 4.3, 4.4, 4.9]
}
df2=pd.DataFrame(employee_data)
df2

   EmployeeID    Name Department  Salary  Rating
0         101     Anu        CSE   60000     4.5
1         102  Bharat       AIML   55000     4.2
2         103  Chetan        CSE   62000     4.8
3         104   Divya        ISE   58000     4.6
4         105    Esha       AIML   61000     4.7
5         106  Farhan        CSE   59000     4.3
6         107  Gaowri        ISE   57000     4.4
7         108  Harish        CSE   63000     4.9

In [ ]:
df2.head()

   EmployeeID    Name Department  Salary  Rating
0         101     Anu        CSE   60000     4.5
1         102  Bharat       AIML   55000     4.2
2         103  Chetan        CSE   62000     4.8
3         104   Divya        ISE   58000     4.6
4         105    Esha       AIML   61000     4.7

In [ ]:
df2.shape

(8, 5)

In [ ]:
print(df2.dtypes)

EmployeeID      int64
Name           object
Department     object
Salary          int64
Rating        float64
dtype: object

In [ ]:
print("mean of salary",df2['Salary'].mean())
print("median of salery",df2['Salary'].median())
print("mode of salery",df2['Salary'].mode())

mean of salary 59375.0
median of salery 59500.0
mode of salery 0    55000
1    57000
2    58000
3    59000
4    60000
5    61000
6    62000
7    63000
Name: Salary, dtype: int64

In [ ]:
df2.describe()

       EmployeeID        Salary    Rating
count     8.00000      8.000000  8.000000
mean    104.50000  59375.000000  4.550000
std       2.44949   2669.269563  0.244949
min     101.00000  55000.000000  4.200000
25%     102.75000  57750.000000  4.375000
50%     104.50000  59500.000000  4.550000
75%     106.25000  61250.000000  4.725000
max     108.00000  63000.000000  4.900000

In [ ]:
df2.isnull()

   EmployeeID   Name  Department  Salary  Rating
0       False  False       False   False   False
1       False  False       False   False   False
2       False  False       False   False   False
3       False  False       False   False   False
4       False  False       False   False   False
5       False  False       False   False   False
6       False  False       False   False   False
7       False  False       False   False   False

In [ ]:
df2.isnull().sum()

EmployeeID    0
Name          0
Department    0
Salary        0
Rating        0
dtype: int64

In [ ]:
df2.duplicated()
df2.duplicated().sum()

np.int64(0)

In [ ]:
print(df[df.duplicated()])

    Student_ID   Name Department Gender  Attendance  Python_Marks  \
10         110  Kiran        ISE      M        80.0          78.0

    Data_Structures_Marks  Final_Score
10                   74.0           76